#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

DEFAULT_SERVICE_ENDPOINT = "http://emr.api.xiaomi.com"
DEFAULT_SECURE_SERVICE_ENDPOINT = "https://emr.api.xiaomi.com"
API_ROOT_PATH = "/v1/api"
SCHEDULER_SERVICE_PATH = "/v1/api/scheduler"
MASTER_SERVICE_PATH = "/v1/api/master"
