# encoding: utf-8
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

SIGNATURE_SUPPORT = {
    1 : False,
    2 : True,
    10 : True,
    11 : True,
    12 : False,
    13 : False,
}
HK_HOST = "host".lower()
HK_TIMESTAMP = "x-xiaomi-Timestamp".lower()
HK_CONTENT_MD5 = "X-Xiaomi-Content-MD5".lower()
HK_AUTHORIZATION = "Authorization".lower()
MI_DATE = "X-Xiaomi-date".lower()
SUGGESTED_SIGNATURE_HEADERS = [
  "Host".lower(),
  "X-Xiaomi-Timestamp".lower(),
  "X-Xiaomi-Content-MD5".lower(),
]
