# encoding: utf-8
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

DEFAULT_CLIENT_TIMEOUT = 10000
DEFAULT_ADMIN_CLIENT_TIMEOUT = 30000
DEFAULT_CLIENT_CONN_TIMEOUT = 3000
DEFAULT_SERVICE_ENDPOINT = "http://sds.api.xiaomi.com"
DEFAULT_SECURE_SERVICE_ENDPOINT = "https://sds.api.xiaomi.com"
API_ROOT_PATH = "/v1/api"
AUTH_SERVICE_PATH = "/v1/api/auth"
ADMIN_SERVICE_PATH = "/v1/api/admin"
TABLE_SERVICE_PATH = "/v1/api/table"
